/**
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
*/
#include <cstdio>

int main()
{
    long fib1 = 1;
    long fib2 = 1;
    long result = 0;
    while (fib2 <= 4000000)
    {
        long next = fib1 + fib2;
        if (next % 2 == 0)
            result += next;
        fib1 = fib2;
        fib2 = next;
    }
    printf("%ld", result);
    return 0;
}
