# -*- coding: utf-8 -*-
"""
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""
fib = [1, 1]
result = 0
while fib[-1] <= 4000000:
    res = fib[-1] + fib[-2]
    fib.append(res)
    if res % 2 == 0:
        result += res

print(result)
